# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\x12\x05lobby\".\n\x0eGeneralRequest\x12\x0e\n\x06sender\x18\x01 \x01(\t\x12\x0c\n\x04\x62ody\x18\x02 \x01(\t\"b\n\x0fGeneralResponse\x12\x10\n\x08sequence\x18\x01 \x01(\x05\x12\x0f\n\x07msgtype\x18\x02 \x01(\x05\x12\x0e\n\x06status\x18\x03 \x01(\x05\x12\x0e\n\x06sender\x18\x04 \x01(\t\x12\x0c\n\x04\x62ody\x18\x05 \x01(\t\"\\\n\tBroadcast\x12\x10\n\x08sequence\x18\x01 \x01(\x05\x12\x0f\n\x07msgtype\x18\x02 \x01(\x05\x12\x0e\n\x06status\x18\x03 \x01(\x05\x12\x0e\n\x06sender\x18\x04 \x01(\t\x12\x0c\n\x04\x62ody\x18\x05 \x01(\t2|\n\x05Lobby\x12\x39\n\x06Handle\x12\x15.lobby.GeneralRequest\x1a\x16.lobby.GeneralResponse\"\x00\x12\x38\n\tSubscribe\x12\x15.lobby.GeneralRequest\x1a\x10.lobby.Broadcast\"\x00\x30\x01\x62\x06proto3')



_GENERALREQUEST = DESCRIPTOR.message_types_by_name['GeneralRequest']
_GENERALRESPONSE = DESCRIPTOR.message_types_by_name['GeneralResponse']
_BROADCAST = DESCRIPTOR.message_types_by_name['Broadcast']
GeneralRequest = _reflection.GeneratedProtocolMessageType('GeneralRequest', (_message.Message,), {
  'DESCRIPTOR' : _GENERALREQUEST,
  '__module__' : 'service_pb2'
  # @@protoc_insertion_point(class_scope:lobby.GeneralRequest)
  })
_sym_db.RegisterMessage(GeneralRequest)

GeneralResponse = _reflection.GeneratedProtocolMessageType('GeneralResponse', (_message.Message,), {
  'DESCRIPTOR' : _GENERALRESPONSE,
  '__module__' : 'service_pb2'
  # @@protoc_insertion_point(class_scope:lobby.GeneralResponse)
  })
_sym_db.RegisterMessage(GeneralResponse)

Broadcast = _reflection.GeneratedProtocolMessageType('Broadcast', (_message.Message,), {
  'DESCRIPTOR' : _BROADCAST,
  '__module__' : 'service_pb2'
  # @@protoc_insertion_point(class_scope:lobby.Broadcast)
  })
_sym_db.RegisterMessage(Broadcast)

_LOBBY = DESCRIPTOR.services_by_name['Lobby']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GENERALREQUEST._serialized_start=24
  _GENERALREQUEST._serialized_end=70
  _GENERALRESPONSE._serialized_start=72
  _GENERALRESPONSE._serialized_end=170
  _BROADCAST._serialized_start=172
  _BROADCAST._serialized_end=264
  _LOBBY._serialized_start=266
  _LOBBY._serialized_end=390
# @@protoc_insertion_point(module_scope)
